name: Rust Test

on:
  push:
    branches: [ "main" ]
    tags:
      - '*' # Triggers release only on tag pushes
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build project
        working-directory: ./multi_threading
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./multi_threading
        run: cargo test --verbose
