name: Rust Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      working-directory: ./multi_threading
      run: cargo build --verbose
      
    - name: Run tests
      working-directory: ./multi_threading
      run: cargo test --verbose
